name: Cucumber Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cucumber:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cucumber tests with @ui tag
        run: |
          ENV=TEST npx cucumber-js --tags "@ui"
          npx ts-node generate-cucmber-report.ts

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: test-results/reports
