name: Run UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cucumber:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run Cucumber tests with @ui tag
        run: npm run test-ui

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: test-results
