name: Run API then UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: |
          npm ci
          npm run test-api
      - uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-json
          path: test-results

  ui-tests:
    name: UI Tests
    needs: api-tests  # 👈 waits for api-tests to complete
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: |
          npm ci
          npx playwright install
          npm run test-ui
      - uses: actions/upload-artifact@v4
        with:
          name: ui-cucumber-json
          path: test-results
