name: UI Tests

on:
  push:
    branches: [main]

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: |
          npm ci
          npx playwright install
          npm run test-ui

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: cucumber-report

      - name: Deploy UI Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cucumber-report
